artifacts_root: artifacts


data_ingestion:
    dataset_name: sartajbhuvaji/brain-tumor-classification-mri
    data_folder_name: data  # artifacts/data


model: # VGG19
    model_folder_name: model  # artifacts/model
    model_path: model/model.h5
    updated_model_path: model/model_updated.h5