artifacts_folder: artifacts


data:
    dataset_name: sartajbhuvaji/brain-tumor-classification-mri
    data_folder_name: data


model: # VGG19
    model_folder_name: model
    model_path: model/model.h5
    updated_model_path: model/model_updated.h5


callbacks:
    folder_name: callbacks
    tensorboard_folder_name: tensorboard
    checkpoint: checkpoint/model.h5


training:
    folder_name: training
    trained_model_path: training/model.h5